#!/usr/bin/env python3
import sys
import os


helpoutput = "Usage: ippi [OPTION] \n\
            List information about the network you are connected to. \n \
\n gui - use the GUI \n \
cli - run the CLI \n  \
            Example: ippi gui \n"
try:
    if sys.argv[1] == "gui":
        print("Starting GUI")
        os.system('./menu_start.py')
        # import menu_start
    elif sys.argv[1] == "cli":
        print("starting CLI")

        import cli
    else:
        print(helpoutput)
except IndexError:
    print(helpoutput)